services:
  database:
      image: postgres:18
      environment:
        POSTGRES_USER: adminuser
        POSTGRES_PASSWORD: adminpassword
        POSTGRES_DB: fullstack_poc_db
      ports:
        - 5432:5432

  api_rest:
    build:
      context: ./API/rest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/fullstack_poc_db
      - SPRING_DATASOURCE_USERNAME=adminuser
      - SPRING_DATASOURCE_PASSWORD=adminpassword
    depends_on:
      - database

  ui_angular:
    build:
      context: ./ui/angular
    ports:
      - "4200:80"
    depends_on:
      - api_rest
